language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.0
    - android-26

    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - unset ANDROID_NDK_HOME

after_success:
  - ./gradlew clean bintrayUploadProject

script:
  - ./gradlew connectedCheck

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle