language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.3
    - android-25

    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - unset ANDROID_NDK_HOME

after_success:
  #- ./gradlew clean mcache:artifactoryPublish mcache-kotlin-extensions:artifactoryPublish
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew connectedCheck

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle