language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.0
    - android-26

    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - openssl aes-256-cbc -K $encrypted_97a2f0459cad_key -iv $encrypted_97a2f0459cad_iv -in codesign.asc.enc -out mcache/codesign.asc -d

env:
  global:
    - secure: "NgSUztC5hZ1LBYSUkbBnvxz3pTQ5G4gM5EpeS6Val3q5kV7ZHxDvO2XwKGmmL0+j/6Dx9Vf0+hnEkhUfPE+sbEuc8PyNd4B2Lujr+qt528CdUqive9LjLppsousCLv+IwuWdquXrY0owAX4UmGAVGomSjG2bWFhULVd1EGt1jgQV5ylXZp9Zgant+Xs6j3CK4462xT/U1t/Or+i7Adxu4qbuQ4HGo2yZZB1SXQOdrx+Kn6NdM3vMD7t49U8Ox3aF7B+fOI0pg09GyFLmqcTBBKWk7Zkx7mklq6HSl+deeMl7BRm/lx4FltSOynVitbxgfsD+M7yBjoKQcI48VceX1Ktk13r569Q33YGkC5XT/aWGXxngQ/m1MVY1yOViSwyjDzVo6m9ZSHiHoSmLgJPEWDgkIVdevFVO5XuPByo2jAhBVfEZaVmbN2RA5NADA9nSaDm5aGyavz4MXpmpCWWfsf9ERw6bu/tHJAKp0xvOgwk03rRp9HfJK6NJJA4SV1iSCE6tsnrKlSWpX8GpzobAI6zm92SyUGUEfRT0UVdH7cVDXItMKT++vW7hdKBU0NSvEkJXc8yibxUa3sLwi9f1QppoW63PE6sq192mwMjM7E0wF2bQJ5g0OtKh0eD0nYAJN96UXU+aN4Ue2A7hHo6h4hjw79RFwLKst/phPLVmdkc="
    - secure: "QuF5qOG7oVTNoCCJ9hjQ7oYDNF1agOXGG8Qz1WwFJgkOLMm0EkB/Co6mBapaZ5rHenHt9BwEQ2wp5TTl4j1H4WwcWS4QZR/66upGh63evdZwNUClyv3awZA4s7Z69ZwDtFEX+a6Lwylr6dYiIFKAlnaCB2BGApX+wlcnP5lwZ9wPS58vp9+RF3pwT/ioAxxH41i/skIpEiyIkHVADpF3znyKM2VgrPuVvGLekDxpCETB0fdeqk5iQC3aHIxNDq8yJOoBcAsLpoLpqx4ijH15K6Fo5cdt8lJImS2Y1EBRjQC2got6uMT25zkCAQ3m7enLhSSAXZ5n+XJOvnth2HvaCs4XQRXAbE24Wkg+MxvEjv2bYWh5vEnR6GCTJYM9uGJO114RLEG4Mz2pegP3RGHNdS4C9Q9Dee4enNV6uf1bdiaGmOpmtYETIaHXVaIiN0p0bd7HP/vV1jEMhmvw/O6oTNTAnhNvlVoWUcC6TjaS3kF20GfToIe5s2uVaB3xCa48gjex4sp4Hmyy3KoEZZsegm6DoQHMrg4OiL+AyDY2qo+8HsTb1P9zyJWkB2rFg7qfvvNGzgedHePnioVRKc00lNRfr35/tngWhxVsQNqjcyV6J3L10dmxyzS8zGtH7CmVuXpKPVD/S6Y5LNdYnW9bFXF5ygDFGZgkT/kiGOmYYa4="
    - secure: "U4iHh4HStINeQzdspkzfmfGxVQHtDzN5ANCo+R9cJWKoL2B/SVbbiZ7zBB+IJY+6/z5+/3pJRtWd7mDEXojN4AIVWiuTQjS1a6mSc5zNyR0bd4U3xrhsExSYN40NMkBi1a3gfHXS3ZBhWac1IuV/qIR2pLsOozMUc1Qx8i5xV+JijBaItwA4B3MTNDzAf8AGfNx6GlGfHSRo90kyfuqF8jQhvDsGnZmj43BlwQwjEWTEpHAwFtUe0hD/Elkhk2dHOwWpotWPOpfkiVVAQqo7hh228vJr6QhW+Bs1haUAl0Xr15s2EbZ3mjCyr+vu6Asf4NKxmML2K+AtLqaVd+fCMp3I+8FW6/lxs17pZ3g01PRPkQIDPhAzdSjmcax7Gb74gOZ7x+JsB7qQQMkZpH+9fopHKarKuGjHI55GZlVzsalUuEdl0b6NKQM1d0roMVRddiMQ43ZGnIj+ZWLLNG255L7vlB5hrJn95eh7lOAyg1k3buEz+Jpp9jf131r/hGSrtJvGPGqu4bCcuvGbDJkoylqAFQYA/WP/o1q64yTjuWrYPyMCju8hR85N9SZJl+wo/TPDnFRZ4gNBs1lIFowyJ4uJfFmzQiMFDzzncDGETMpQVCrUKcJl7nwI0CTo96cFSZhsskxApy78QuT0247j3qekKEI2cokqFy8uVcJxN5k="
    - secure: "E8b6FxSrItpJo7wUuQivKfvJAqmh7VZscueHLQFcPLfO0sUkkWak1Mz1G8nYMfZM8uUkik05JaE6sQJ7gfp9EtQsy6iqahlZ6Z04eTsLI3AJE6nG000jM5X/qw5poCzNZfUEWLpSVaMZZf3KhPlr97uW35fWQ/svOS1Lvc/QbdhhGW2OdLdzjP5wgZux1u2MrI9STMDvAenCwsPI0dSeg/X7Q2QXDDyHqxOm2TOYLiGjEbXRUzw3eEmlXHzIN6qSWssdKNqWWlH4zVBWOEHLMSzuFVJfs7kmChd2uELfoqOLJ7sFsA/0qkq2z75iCOEt0N1crFLuzGfnsWtxCdHGLYuCKmyj9ofPfapnlJh7yDbKFPguYw3kpTZPZBUkHQwKVHLzvRhI0dkk2/kmc6hEufAG0RZbQ46k6oXQs92IWAm+BhC/7ARDY58WUC6zKxFpwEb/liZeTMlH6cqbQ6kVucTRplofSFJN2CrtDSj33ceWy4xHgtlqMlKO3nzKsFih42VHAltIQPwXpEK5s5drWNs0SarGbeZxutd19Bx9NOvvkFVBVSnFVvwOhRaTKYwiAISfoaJpWTU3ky5Dr6zeiePbuj8ax9rYMnt4EKQFkai9R6TN41/37KxO8GaZ90uGH65zKnWWkRqXjA8patkVBimRzcGTHtx6vgW5aLbUtFQ="

before_script:
  - unset ANDROID_NDK_HOME

after_success:
  - ./gradlew clean bintrayUploadProject

script:
  - ./gradlew connectedCheck

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle